import { IsString, IsNotEmpty, IsOptional, IsBoolean, IsNumber, IsUUID } from "class-validator";
import { Type } from "class-transformer";

export class CreateCustomerDto {
  @IsOptional() @IsString() old_erp_customer_code?: string;
  @IsString() @IsNotEmpty() customer_name: string;
  @IsString() @IsNotEmpty() customer_short_name: string;
  @IsString() @IsNotEmpty() customer_type: string;
  @IsOptional() @IsString() customer_source?: string;
  @IsOptional() @IsString() industry_type?: string;
  @IsOptional() @IsString() unified_business_no?: string;
  @IsOptional() @IsString() medical_institution_code?: string;
  @IsOptional() @IsString() contact_person?: string;
  @IsOptional() @IsString() contact_position?: string;
  @IsOptional() @IsString() contact_phone?: string;
  @IsOptional() @IsString() mobile_phone?: string;
  @IsOptional() @IsString() contact_email?: string;
  @IsString() @IsNotEmpty() phone: string;
  @IsOptional() @IsString() website?: string;
  @IsOptional() @IsString() email?: string;
  @IsString() @IsNotEmpty() company_zip_code: string;
  @IsString() @IsNotEmpty() company_address: string;
  @IsOptional() @IsString() business_hours_start?: string;
  @IsOptional() @IsString() business_hours_end?: string;
  @IsOptional() @IsString() payment_terms?: string;
  @IsOptional() @Type(() => Number) @IsNumber() closing_day?: number;
  @IsOptional() @Type(() => Number) @IsNumber() invoice_date?: number;
  @IsOptional() @Type(() => Number) @IsNumber() credit_days?: number;
  @IsOptional() @Type(() => Number) @IsNumber() credit_limit?: number;
  @IsOptional() @IsBoolean() contract_signed?: boolean;
  @IsOptional() @IsBoolean() allow_transaction?: boolean;
  @IsOptional() @IsString() region_code?: string;
  @IsOptional() @IsString() shipping_address?: string;
  @IsOptional() @IsString() shipping_recipient?: string;
  @IsOptional() @IsString() shipping_recipient_phone?: string;
  @IsOptional() @IsString() billing_address?: string;
  @IsOptional() @IsString() billing_recipient?: string;
  @IsOptional() @IsString() billing_recipient_phone?: string;
  @IsOptional() @IsString() invoice_remark?: string;
  @IsOptional() @IsString() shipping_zip?: string;
  @IsOptional() @IsString() billing_zip?: string;
  @IsOptional() @IsString() bank_name?: string;
  @IsOptional() @IsString() bank_account?: string;
  @IsOptional() @IsString() bank_account_name?: string;
  @IsOptional() @IsString() invoice_tax_id?: string;
  @IsUUID() @IsNotEmpty() company_id: string;
  @IsUUID() @IsNotEmpty() tenant_id: string;
}

export class UpdateCustomerDto {
  @IsOptional() @IsNumber() latitude?: number;
  @IsOptional() @IsNumber() longitude?: number;
  @IsOptional() @IsString() old_erp_customer_code?: string;
  @IsOptional() @IsString() customer_name?: string;
  @IsOptional() @IsString() customer_short_name?: string;
  @IsOptional() @IsString() customer_type?: string;
  @IsOptional() @IsString() customer_source?: string;
  @IsOptional() @IsString() industry_type?: string;
  @IsOptional() @IsString() unified_business_no?: string;
  @IsOptional() @IsString() medical_institution_code?: string;
  @IsOptional() @IsString() contact_person?: string;
  @IsOptional() @IsString() contact_position?: string;
  @IsOptional() @IsString() contact_phone?: string;
  @IsOptional() @IsString() mobile_phone?: string;
  @IsOptional() @IsString() contact_email?: string;
  @IsOptional() @IsString() phone?: string;
  @IsOptional() @IsString() website?: string;
  @IsOptional() @IsString() email?: string;
  @IsOptional() @IsString() company_zip_code?: string;
  @IsOptional() @IsString() company_address?: string;
  @IsOptional() @IsString() business_hours_start?: string;
  @IsOptional() @IsString() business_hours_end?: string;
  @IsOptional() @IsString() payment_terms?: string;
  @IsOptional() @Type(() => Number) @IsNumber() closing_day?: number;
  @IsOptional() @Type(() => Number) @IsNumber() invoice_date?: number;
  @IsOptional() @Type(() => Number) @IsNumber() credit_days?: number;
  @IsOptional() @Type(() => Number) @IsNumber() credit_limit?: number;
  @IsOptional() @IsBoolean() contract_signed?: boolean;
  @IsOptional() @IsBoolean() allow_transaction?: boolean;
  @IsOptional() @IsString() region_code?: string;
  @IsOptional() @IsString() customer_id?: string;
  @IsOptional() @IsString() customer_code?: string;
  @IsOptional() @IsString() credit_status?: string;
  @IsOptional() @Type(() => Number) @IsNumber() outstanding_ar?: number;
  @IsOptional() @Type(() => Number) @IsNumber() consignment_balance?: number;
  @IsOptional() @IsString() pause_start_date?: string;
  @IsOptional() @IsString() company_id?: string;
  @IsOptional() @IsString() tenant_id?: string;
  @IsOptional() @IsString() owning_employee_id?: string;
  @IsOptional() @IsString() customer_status?: string;
  @IsOptional() @Type(() => Number) @IsNumber() total_sample_count?: number;
  @IsOptional() @IsString() import_source?: string;
  @IsOptional() @IsString() created_at?: string;
  @IsOptional() @IsString() created_by?: string;
  @IsOptional() @IsString() updated_at?: string;
  @IsOptional() @IsString() updated_by?: string;
  @IsOptional() @IsString() deleted_at?: string;
  @IsOptional() owning_employee?: any;
  @IsOptional() company?: any;
  @IsOptional() working_days?: string;
  @IsOptional() holidays?: string;
  @IsOptional() @IsString() shipping_address?: string;
  @IsOptional() @IsString() shipping_recipient?: string;
  @IsOptional() @IsString() shipping_recipient_phone?: string;
  @IsOptional() @IsString() billing_address?: string;
  @IsOptional() @IsString() billing_recipient?: string;
  @IsOptional() @IsString() billing_recipient_phone?: string;
  @IsOptional() @IsString() invoice_remark?: string;
  @IsOptional() @IsString() shipping_zip?: string;
  @IsOptional() @IsString() billing_zip?: string;
  @IsOptional() @IsString() bank_name?: string;
  @IsOptional() @IsString() bank_account?: string;
  @IsOptional() @IsString() bank_account_name?: string;
  @IsOptional() @IsString() invoice_tax_id?: string;
}