-- ============================================
-- 种子数据: 角色 / 权限 / 枚举 / 系统参数 / 纸张格式
-- ============================================

-- 初始化角色
INSERT INTO role (role_code, role_name, description, is_system) VALUES
('SALES', '基层业务', '客户开发、拜访、销售订单', TRUE),
('REGION_MANAGER', '区域经理', '管辖片区全部客户及下属业务员', TRUE),
('SALES_DIRECTOR', '业务总监', '全公司业务监督', TRUE),
('FINANCE', '财务', '应收/应付、费用、成本核算', TRUE),
('FINANCE_CLERK', '财务专员', '日常财务操作', TRUE),
('QA', '品保', '品质检验、Recall管理', TRUE),
('QA_DIRECTOR', '品保总监', '品保终审、重新开启Recall', TRUE),
('GM', '总经理', '经营决策、终审', TRUE),
('EXECUTIVE_DIRECTOR', '执行董事', '重大事项终审', TRUE),
('ADMIN', '系统管理员', '系统配置、权限分配、安全负责人', TRUE),
('DATA_MIGRATOR', '资料迁移专员', '批量导入任务管理', TRUE),
('WAREHOUSE', '仓管', '收货、上架、拣货、出货、盘点', TRUE);

-- 初始化纸张格式
INSERT INTO paper_format (format_code, format_name, width_mm, height_mm, is_default) VALUES
('A4', 'A4 (210×297mm)', 210, 297, TRUE),
('A5', 'A5 (148×210mm)', 148, 210, FALSE),
('ZHONGYIDAO', '中一刀 (9.5"×11")', 241, 279, FALSE),
('THERMAL_80', '热敏 80mm', 80, 99999, FALSE);

-- 初始化动态枚举
INSERT INTO enum_value (enum_type, enum_code, enum_label, sort_order) VALUES
('customer_type', 'HOSPITAL', '医院', 1),
('customer_type', 'CLINIC', '诊所', 2),
('customer_type', 'DISTRIBUTOR', '经销商', 3),
('customer_type', 'PARTNER', '同行合作', 4),
('customer_type', 'PERSONAL', '个人医师', 5),
('payment_terms', 'CASH', '现金/现汇', 1),
('payment_terms', 'NET_30', '票到30天', 2),
('payment_terms', 'NET_45', '票到45天', 3),
('payment_terms', 'NET_60', '票到60天', 4),
('payment_terms', 'MONTHLY_BY_CLOSING', '月结（结账日+请款日）', 5),
('recall_level', 'R1', '观察', 1),
('recall_level', 'R2', '内部限制', 2),
('recall_level', 'R3', '正式召回', 3),
('recall_level', 'R4', '紧急召回', 4),
('product_category', 'DEVICE', '医疗器材', 1),
('product_category', 'COSMETIC', '化妆品', 2),
('product_category', 'CONSUMABLE', '耗材', 3),
('region_code', 'NORTH', '北区', 1),
('region_code', 'CENTRAL', '中区', 2),
('region_code', 'SOUTH', '南区', 3),
('customer_status', 'LEAD', '线索', 1),
('customer_status', 'DEVELOPING', '开发中', 2),
('customer_status', 'SAMPLING', '打板中', 3),
('customer_status', 'A', 'A级客户', 4),
('customer_status', 'B', 'B级客户', 5),
('customer_status', 'C', 'C级客户', 6),
('customer_status', 'VIP', 'VIP客户', 7),
('customer_status', 'INACTIVE', '停用', 8),
('sample_purpose', 'PRODUCT_TEST', '产品测试', 1),
('sample_purpose', 'CLINICAL_TRIAL', '临床试验', 2),
('sample_purpose', 'PROMOTION', '推广活动', 3),
('sample_purpose', 'COMPETITOR_ANALYSIS', '竞品分析', 4),
('visit_result', 'INTERESTED', '有兴趣', 1),
('visit_result', 'NOT_INTERESTED', '无兴趣', 2),
('visit_result', 'NEED_FOLLOWUP', '需追踪', 3),
('visit_result', 'READY_TO_ORDER', '准备下单', 4),
('visit_result', 'NEED_SAMPLE', '需样品', 5),
('visit_result', 'NEED_QUOTE', '需报价', 6),
('visit_result', 'PRICE_ISSUE', '有价格问题', 7),
('visit_result', 'PAYMENT_ISSUE', '有回款问题', 8),
('visit_result', 'CONSIGN_ISSUE', '有寄库问题', 9),
('visit_result', 'NEED_ACADEMIC', '需学术支持', 10),
('customer_source', 'COLD_CALL', '陌生开发', 1),
('customer_source', 'REFERRAL', '客户转介', 2),
('customer_source', 'EXHIBITION', '展会', 3),
('customer_source', 'ONLINE', '线上来源', 4),
('customer_source', 'IMPORT', '系统导入', 5),
('customer_source', 'OTHER', '其他', 6),
('industry_type', 'MEDICAL_CENTER', '医学中心', 1),
('industry_type', 'REGIONAL_HOSPITAL', '区域医院', 2),
('industry_type', 'LOCAL_HOSPITAL', '地区医院', 3),
('industry_type', 'PRIVATE_CLINIC', '私人诊所', 4),
('industry_type', 'BEAUTY_CLINIC', '医美诊所', 5),
('industry_type', 'PHARMACY', '药局', 6),
('industry_type', 'DISTRIBUTOR_CHANNEL', '经销通路', 7),
('warehouse_type', 'MAIN', '总仓', 1),
('warehouse_type', 'BRANCH', '分仓', 2),
('warehouse_type', 'CONSIGNMENT_ZONE', '寄库区', 3),
('warehouse_type', 'RECALL_ZONE', '召回隔离区', 4),
('warehouse_type', 'QA_ZONE', 'QA待验区', 5),
('warehouse_type', 'DEFECTIVE_ZONE', '不良品区', 6);

-- 初始化系统参数
INSERT INTO system_param (param_key, param_value, param_type, description) VALUES
('ar_reminder_days_before_due', '[7,3,1]', 'ARRAY', '应收到期前提醒天数'),
('ar_overdue_reminder_interval_days', '1', 'NUMBER', '逾期催收间隔天数'),
('ar_upgrade_overdue_days', '7', 'NUMBER', '逾期升级经理天数'),
('ar_block_order_overdue_days', '30', 'NUMBER', '逾期锁单天数'),
('consignment_stale_days', '90', 'NUMBER', '寄库呆滞预警天数'),
('sample_feedback_reminder_interval_days', '10', 'NUMBER', '打板反馈提醒间隔'),
('print_max_concurrent_pages', '5', 'NUMBER', '打印引擎最大并发'),
('emergency_complete_days', '3', 'NUMBER', '紧急采购补单天数'),
('low_price_reject_limit', '2', 'NUMBER', '低价审批驳回次数锁定阈值'),
('sos_fingerprint_enabled', 'true', 'BOOLEAN', '启用指纹SOS'),
('sos_pin_code', '1919', 'STRING', 'SOS安全PIN码'),
('sos_long_press_seconds', '3', 'NUMBER', 'SOS长按触发秒数'),
('device_binding_max', '3', 'NUMBER', '设备绑定最大数量'),
('import_max_file_size_mb', '50', 'NUMBER', '导入文件最大MB'),
('import_batch_size', '500', 'NUMBER', '导入批次大小'),
('gps_allowed_error_meters', '100', 'NUMBER', 'GPS允许误差(米)'),
('gps_upload_interval_seconds', '30', 'NUMBER', 'GPS上传间隔(秒)'),
('gps_min_stay_minutes', '5', 'NUMBER', '最低停留时间(分钟)'),
('ar_suspend_max_days', '30', 'NUMBER', '催收暂停最大天数'),
('budget_adjust_large_threshold_pct', '20', 'NUMBER', '预算调整大幅阈值(%)');

